GRANT ALL ON SCHEMA public TO editor, basic_user;

GRANT USAGE
  ON SCHEMA public
  TO scheduler;

ALTER DEFAULT PRIVILEGES
FOR ROLE basic_user
IN SCHEMA public
GRANT ALL ON TABLES TO editor;

ALTER DEFAULT PRIVILEGES
FOR ROLE basic_user
IN SCHEMA public
GRANT ALL ON SEQUENCES TO editor;

ALTER DEFAULT PRIVILEGES
FOR ROLE basic_user
IN SCHEMA public
GRANT EXECUTE ON FUNCTIONS TO editor;