DROP SCHEMA IF EXISTS lad CASCADE;

CREATE SCHEMA IF NOT EXISTS lad;

ALTER SCHEMA lad OWNER TO editor;

GRANT USAGE ON SCHEMA lad TO basic_user;

GRANT USAGE
  ON SCHEMA lad
  TO scheduler;

ALTER DEFAULT PRIVILEGES
FOR ROLE editor
IN SCHEMA lad
GRANT SELECT ON TABLES TO basic_user;

ALTER DEFAULT PRIVILEGES
FOR ROLE editor
IN SCHEMA lad
GRANT SELECT ON SEQUENCES TO basic_user;