DROP SCHEMA IF EXISTS mvr CASCADE;

CREATE SCHEMA IF NOT EXISTS mvr;

ALTER SCHEMA mvr OWNER TO editor;

GRANT USAGE ON SCHEMA mvr TO basic_user;

GRANT USAGE
  ,CREATE
  ON SCHEMA mvr
  TO scheduler;

ALTER DEFAULT PRIVILEGES
FOR ROLE editor
IN SCHEMA mvr
GRANT SELECT ON TABLES TO basic_user;

ALTER DEFAULT PRIVILEGES
FOR ROLE editor
IN SCHEMA mvr
GRANT SELECT ON SEQUENCES TO basic_user;

ALTER DEFAULT PRIVILEGES
FOR ROLE scheduler
IN SCHEMA mvr
GRANT ALL ON TABLES TO editor;

ALTER DEFAULT PRIVILEGES
FOR ROLE scheduler
IN SCHEMA mvr
GRANT SELECT ON TABLES TO basic_user;

ALTER DEFAULT PRIVILEGES
FOR ROLE scheduler
IN SCHEMA mvr
GRANT ALL ON SEQUENCES TO editor;

ALTER DEFAULT PRIVILEGES
FOR ROLE scheduler
IN SCHEMA mvr
GRANT SELECT ON SEQUENCES TO basic_user;