DROP SCHEMA IF EXISTS vzd CASCADE;

CREATE SCHEMA IF NOT EXISTS vzd;

ALTER SCHEMA vzd OWNER TO editor;

GRANT USAGE ON SCHEMA vzd TO basic_user;

GRANT USAGE
  ,CREATE
  ON SCHEMA vzd
  TO scheduler;

ALTER DEFAULT PRIVILEGES
FOR ROLE editor
IN SCHEMA vzd
GRANT SELECT ON TABLES TO basic_user;

ALTER DEFAULT PRIVILEGES
FOR ROLE editor
IN SCHEMA vzd
GRANT SELECT ON SEQUENCES TO basic_user;

ALTER DEFAULT PRIVILEGES
FOR ROLE scheduler
IN SCHEMA vzd
GRANT ALL ON TABLES TO editor;

ALTER DEFAULT PRIVILEGES
FOR ROLE scheduler
IN SCHEMA vzd
GRANT SELECT ON TABLES TO basic_user;

ALTER DEFAULT PRIVILEGES
FOR ROLE scheduler
IN SCHEMA vzd
GRANT ALL ON SEQUENCES TO editor;

ALTER DEFAULT PRIVILEGES
FOR ROLE scheduler
IN SCHEMA vzd
GRANT SELECT ON SEQUENCES TO basic_user;